### ISSUE TITLE
Infografia ciclo de vida del desarrollo de un sistema

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-1-infografia-santiagomary1004#2]
Elaborado por: Maribel Santiago Bautista 22620262
[Infografia_Maribel_Santiago_Bautista.pdf](https://github.com/user-attachments/files/16843063/Infografia_Maribel_Santiago_Bautista.pdf)

**Comment by evelyn-santiago** [comment]
20/20
cumple con todos los criterios de evaluación

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
